AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 that enables SSH
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ab4d1e9cf9a1215a
      InstanceType: t2.micro
      KeyName: ec2_key
      SecurityGroups:
        - cf_demo
      Tags:
        - Key: Name
          Value: charlie-cf-stack-instance
        - Key: Department
          Value: hr